mybatis:
  #  通过yml配置文件的方式解放了mybatis-config.xml文件
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mp?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver